spring:
  application:
    name=Api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpclient:
        wiretap: true
        httpserver:
          wiretap: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
            allowedHeaders: "*"
            maxAge: 3600

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE