server:
  port: 8082

spring:
  application:
    name: event-service
  cloud:
    discovery:
      enabled: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        http:
          DEBUG
        web:
          DEBUG
        security:
          DEBUG