server:
  port: 8082

spring:
  application:
    name: event-service
  cloud:
    discovery:
      enabled: true

  gateway:
    httpclient:
      wiretap: true
      httpserver:
        wiretap: true
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "http://localhost:4200"
          allowedMethods:
            - GET
              - POST

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        http:
          DEBUG
        web:
          DEBUG
        security:
          DEBUG